
tasks:
  - before: sdk install java 21.0.7-oracle
  - init: ./gradlew build
  - name: test
    command: ./gradlew test
vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
