
tasks:
  - init: sdk install java 21.0.7-oracle && ./gradlew build
  - name: Build and test with gradle
    command: sdk install java 21.0.7-oracle && ./gradlew test
vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
