
tasks:
  - name: Install JDK 21 Oracle and build project
    command: sdk install java 21.0.7-oracle && ./gradlew clean build
vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
