#!/bin/bash

echo "starting Theia IDE"
name=theia-$(basename $PWD)
touch $(pwd)/theia.secret
docker run -d -v $(pwd):/home/project:cached --env-file $(pwd)/theia.secrets --name $name -p 3000:3000 rossonet/linneo-theia:latest
echo "container with name $name started"
sleep 5
xdg-open http://localhost:3000
