rootProject.name = 'WaldOT'
include 'waldot-api'
include 'waldot-deps'
include 'waldot-namespace'
include 'waldot-app'
include 'waldot-client'
project(':waldot-client').projectDir = file('clients/waldot-client')
include 'wotctl'
project(':wotctl').projectDir = file('clients/wotctl')
include 'waldot-plugin-tinkerpop'
project(':waldot-plugin-tinkerpop').projectDir = file('plugins/waldot-plugin-tinkerpop')
include 'waldot-plugin-rules-engine'
project(':waldot-plugin-rules-engine').projectDir = file('plugins/waldot-plugin-rules-engine')
include 'waldot-plugin-generator'
project(':waldot-plugin-generator').projectDir = file('plugins/waldot-plugin-generator')
