package net.rossonet.cli;

import net.rossonet.cli.jline.TerminalHelper;

public enum BrandSelector {

	OLIVETTI(TerminalHelper.ANSI_CYAN, TerminalHelper.ANSI_RED, "olivetti.txt", TerminalHelper.ANSI_BLUE,
			TerminalHelper.ANSI_BLUE, TerminalHelper.ANSI_RED, TerminalHelper.ANSI_GREEN, "password123",
			"generated by Linneo", true, true, "Olivetti experimental system", "andrea.ambrosini@rossonet.com"),
	ROSSONET(TerminalHelper.ANSI_CYAN, TerminalHelper.ANSI_RED, "rossonet.txt", TerminalHelper.ANSI_BLUE,
			TerminalHelper.ANSI_BLUE, TerminalHelper.ANSI_RED, TerminalHelper.ANSI_GREEN, "password123",
			"generated by WaldOT", true, true, "WaldOT Control System", "andrea.ambrosini@rossonet.com");

	private final String additionalPromptColor;
	private final boolean aiEnabled;
	private final String baseHelperFile;
	private final String contactMail;
	private final boolean experimentalEnabled;
	private final String factoryPassword;
	private final String generatedByComment;
	private final String historyLineColor;
	private final String historyRemoteAddressColor;

	private final String historyUserColor;

	private final String promptHostColor;
	private final String promptUserColor;
	private final String softwareDescriptionShort;

	BrandSelector(final String additionalPromptColor, final String historyLineColor, final String baseHelperFile,
			final String historyRemoteAddressColor, final String historyUserColor, final String promptHostColor,
			final String promptUserColor, final String factoryPassword, final String generatedByComment,
			final boolean experimentalEnabled, final boolean aiEnabled, final String softwareDescriptionShort,
			final String contactMail) {
		this.additionalPromptColor = additionalPromptColor;
		this.historyLineColor = historyLineColor;
		this.historyRemoteAddressColor = historyRemoteAddressColor;
		this.historyUserColor = historyUserColor;
		this.promptHostColor = promptHostColor;
		this.promptUserColor = promptUserColor;
		this.factoryPassword = factoryPassword;
		this.generatedByComment = generatedByComment;
		this.experimentalEnabled = experimentalEnabled;
		this.aiEnabled = aiEnabled;
		this.baseHelperFile = baseHelperFile;
		this.softwareDescriptionShort = softwareDescriptionShort;
		this.contactMail = contactMail;
	}

	private String generateHelpFile() {
		// TODO Auto-generated method stub
		return "this is a placeholder for " + baseHelperFile;
	}

	public String getAdditionalPromptColor() {
		return additionalPromptColor;
	}

	public String getBaseHelperFile() {
		return generateHelpFile();
	}

	public String getContactMail() {
		return contactMail;
	}

	public String getFactoryPassword() {
		return factoryPassword;
	}

	public String getGeneratedByComment() {
		return generatedByComment;
	}

	public String getHistoryLineColor() {
		return historyLineColor;
	}

	public String getHistoryRemoteAddressColor() {
		return historyRemoteAddressColor;
	}

	public String getHistoryUserColor() {
		return historyUserColor;
	}

	public String getPromptHostColor() {
		return promptHostColor;
	}

	public String getPromptUserColor() {
		return promptUserColor;
	}

	public String getSoftwareDescriptionShort() {
		return softwareDescriptionShort;
	}

	public boolean isAiEnabled() {
		return aiEnabled;
	}

	public boolean isExperimentalEnabled() {
		return experimentalEnabled;
	}

}
