name: Build native and man page on master branch with Gradle

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.0'
        java-version: '17'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'
    - name: Clone sub repos
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        git submodule init
        git submodule update
    - name: Build native with Gradle
      run: ./gradlew generateManpageAsciiDoc nativeCompile -Dorg.gradle.daemon=false
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: console-app-${{ matrix.os }}
        path: build/native/nativeCompile/TemplateConsoleApplication
